spring.application.name=sistema-academico

# Conexao
spring.datasource.url=jdbc:mysql://localhost:3306/academico
spring.datasource.username=root
spring.datasource.password=${SUA_SENHA}

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
# Ignora erro de checksum para permitir o boot
spring.flyway.validate-on-migrate=false
